import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:palengkego/core/config/app_config.dart';
import 'package:palengkego/firebase_options.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Firebase SDK instance providers
// These are safe to keep — they are only accessed when Firebase is actually
// initialized (i.e. when firebaseEnabled == true).
// ─────────────────────────────────────────────────────────────────────────────

/// Provider for Firebase Auth instance.
final firebaseAuthProvider = Provider<FirebaseAuth>((ref) {
  return FirebaseAuth.instance;
});

/// Provider for Cloud Firestore instance.
final firestoreProvider = Provider<FirebaseFirestore>((ref) {
  return FirebaseFirestore.instance;
});

/// Provider for Firebase Storage instance.
final firebaseStorageProvider = Provider<FirebaseStorage>((ref) {
  return FirebaseStorage.instance;
});

/// Convenience provider — reads the FIREBASE_ENABLED dart-define flag
/// from [AppConfig] so any provider can check it without importing AppConfig.
final firebaseEnabledProvider = Provider<bool>((ref) {
  return ref.watch(appConfigProvider).firebaseEnabled;
});

// ─────────────────────────────────────────────────────────────────────────────
// FirebaseService — handles app startup initialization
// ─────────────────────────────────────────────────────────────────────────────

class FirebaseService {
  /// Initializes Firebase with the platform options generated by
  /// `flutterfire configure` (`lib/firebase_options.dart`, gitignored).
  ///
  /// Should only be called when [AppConfig.firebaseEnabled] is true.
  /// Throws when Firebase cannot be initialized — callers decide whether
  /// that is fatal (production) or a log-and-continue (development).
  static Future<void> initialize() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }
}
